# Site settings
title: Great British Breaks
client:
  name: TouchNote
  link: https://touchnote.com/uk-partnerships-secret-escapes/
  download-link: https://touchnote.onelink.me/3205415180?pid=Partnerships&c=TouchNote-Secret%20Escapes_ESCAPE&af_dp=tn%3A%2F%2Fpromocode%2FESCAPE&af_web_dp=https%3A%2F%2Fapp.touchnote.com%2Fa%2FPROMO%2FESCAPE
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Sometimes our busy lives get in the way of what really matters. That’s why together with Touchnote, a membership service for real personalised photo cards sent from your phone, we’re helping you reconnect with a loved one on a great British Break. Capture those moments that only travel can bring with TouchNote, and share your memories with those you love.


# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/great-british-breaks" # the subpath of the site, including territory and year
img:     "/uk/2020/great-british-breaks/_assets/img"
css:     "/uk/2020/great-british-breaks/_assets/css"
js:      "/uk/2020/great-british-breaks/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed