# Site settings
title: Great British Breaks
client:
  name: TouchNote
  link: https://touchnote.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Sometimes, nothing beats a quick getaway in Britain. A seaside jaunt, a lakeside ramble, a cosy country getaway; load up the car, hop on the train, and head out for that quintessential British pastime: the great British Break.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/great-british-breaks" # the subpath of the site, including territory and year
img:     "/uk/2020/great-british-breaks/_assets/img"
css:     "/uk/2020/great-british-breaks/_assets/css"
js:      "/uk/2020/great-british-breaks/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed